### ISSUE TITLE
Heyzap is now Fyber Fairbid

### ISSUE THREAD

**Issue by hwde** [jim-lake/react-native-hzads#2]
Hey, android seems to already use fairbid, but iOS is still on heyzap. Any plans to switch it too?

**Comment by jim-lake** [comment]
Neither use the fairbid SDK which is version 2.3.0 which is the real new SDK.  I'm probably going to make a new module for it, as your old API key does not work with the new SDK.  The ideal situation is a API from the react-native side that's identical and supports FairBid 2.3.0 instead of the old SDK.
